# Blog settings
permalink: /works/:categories/:title


# My variables
name: your-name-here
description: works and infos
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
